### ISSUE TITLE
`SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE` seems to be ignored

### ISSUE THREAD

**Issue by neshtea** [kristophjunge/docker-test-saml-idp#29]
# Description
First of all, thanks for providing this docker image, it helps a lot!

It is my understanding that when logging out a user via the web interface, `simplesaml` should send a logout request to the configured `SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE`.

# Observation
The IdP contacts the acs **but not the sls**.

# Setup
I've got an application running as the service provider, configured like this (excerpt from my `docker-compose.yml` file:

``` yml
test-saml-idp:
    image: kristophjunge/test-saml-idp:1.15
    container_name: saml-idp
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: "http://localhost:3449/saml/metadata"
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "http://localhost:3449/saml/login"
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: "http://localhost:3449/saml/logout"
    volumes:
      - ./docker-saml/users.php:/var/www/simplesamlphp/config/authsources.php:ro
```

Login works as expected. If the login is successful, the `/saml/login` endpoint is contacted carrying the expected data.
On logout, my service provider is not contacted. Through other means, I verified that in principle, `/saml/logout` receives requests and does "the right thing".

# Request
It would help if you could verify one of these assertions:
1. My setup is wrong (and perhaps how to fix it).
2. My assumption that the IdP contacts the SP via `/saml/logout` is wrong.
3. This is indeed a bug.

Thank you!
